#! /bin/bash -e

dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${dir}

# get latest version of NFI
wget 'https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX.py' -O user_data/strategies/NostalgiaForInfinityX.py
wget 'https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityNext.py' -O user_data/strategies/NostalgiaForInfinityNext.py
wget 'https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityNextGen.py' -O user_data/strategies/NostalgiaForInfinityNextGen.py


timeframes=("5m" "15m" "1h" "1d")

for tf in ${timeframes[@]}; do
	docker-compose run --rm freqtrade download-data --erase --config /freqtrade/user_data/configs/config-whitelist.json --exchange binance -t ${tf}
done


docker-compose run --rm freqtrade backtesting --config /freqtrade/user_data/configs/config.json --config /freqtrade/user_data/configs/config-whitelist.json --config /freqtrade/user_data/configs/config-blacklist.json --datadir user_data/data/binance --export trades  --stake-amount 500 -s NostalgiaForInfinityX
