---
version: '3'
services:
  freqtrade:
    build:
      context: .
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade-dev
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/configs/config.json
      --config /freqtrade/user_data/configs/config-prd.json
      --config /freqtrade/user_data/configs/config-whitelist.json
      --config /freqtrade/user_data/configs/config-blacklist.json
      --config /freqtrade/user_data/configs/config-pairlist-volume-binance-usdt.json
      --strategy Zeus
